# Generated by Django 2.0.1 on 2018-05-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.CharField(max_length=20, verbose_name='产品类别')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('subhead', models.CharField(max_length=100, verbose_name='副标题')),
                ('description', models.CharField(max_length=400, verbose_name='描述')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
