# Generated by Django 2.0.1 on 2018-05-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_products_imgurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imgurl',
            field=models.CharField(default='', max_length=100, verbose_name='图片地址'),
        ),
    ]
