# Generated by Django 2.0.1 on 2018-05-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_products_imgurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(null=True, upload_to='img/goods', verbose_name='图片'),
        ),
    ]
