# Generated by Django 2.0.1 on 2018-06-05 03:09

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20180529_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Content',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容\t'),
        ),
    ]
