# Generated by Django 2.0.1 on 2018-07-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0009_auto_20180624_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='imgurl2',
            field=models.CharField(default='', max_length=500, verbose_name='图片地址2'),
        ),
        migrations.AddField(
            model_name='products',
            name='imgurl3',
            field=models.CharField(default='', max_length=500, verbose_name='图片地址3'),
        ),
    ]
