# Generated by Django 2.0.1 on 2018-07-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_auto_20180724_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='products',
            name='update_time',
        ),
    ]
