# Generated by Django 2.0.1 on 2018-08-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20180725_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='imgurl3',
        ),
    ]
