# Generated by Django 2.0.1 on 2018-08-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_auto_20180804_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='imgurl2',
            field=models.CharField(default='', max_length=1000, verbose_name='图片地址2'),
        ),
    ]
