# Generated by Django 2.0.1 on 2018-08-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20180826_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='imgurl2',
            field=models.TextField(default='', verbose_name='图片地址2'),
        ),
    ]
