# Generated by Django 2.0.1 on 2018-07-24 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='update_time',
        ),
    ]
